---
apiVersion: v1
kind: Namespace
metadata:
  name: prod

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-prod-secret
  namespace: prod
type: Opaque
stringData:
  postgres-username: "appuser"
  postgres-password: "MyStr0ngPass!"   # ⚠️ change this
  postgres-database: "appdb_prod"

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: prod
type: Opaque
stringData:
  db-password: "MyStr0ngPass!"         # ⚠️ must match postgres-prod-secret password

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: prod
type: Opaque
stringData:
  admin-password: "MyStr0ngPass!"      # ⚠️ change this