---
# Registers argocd-vault-plugin-helm as a custom plugin in ArgoCD
# Place this in: argocd/avp/argocd-cm-plugin.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-helm
    spec:
      allowConcurrency: true
      discover:
        find:
          command: [sh, -c, "find . -name 'Chart.yaml' | head -1"]
      generate:
        command: [sh, -c]
        args:
          - |
            helm dependency build && \
            helm template $ARGOCD_APP_NAME . \
              $(echo $HELM_VALUES_FILES | tr ',' '\n' | sed 's/^/-f /') \
              | argocd-vault-plugin generate -
      lockRepo: false

# Where (argocd-vault-plugin) It Comes  From 
# it is from
# argocd-vault-plugin.yaml (in argocd/apps/)
#         │
#         ▼
# ArgoCD installs this as a Helm chart
#         │
#         ▼
# Downloads AVP binary from GitHub releases
# https://github.com/argoproj-labs/argocd-vault-plugin
#         │
#         ▼
# Copies binary into argocd-repo-server pod at:
# /usr/local/bin/argocd-vault-plugin

# HELM_VALUES_FILES is an environment variable that you set yourself in the ArgoCD Application manifest. (apps)
# ArgoCD sees plugin: argocd-vault-plugin-helm
#         │
#         ▼
# Runs INIT:
#   helm dependency build
#         │
#         ▼
# Runs GENERATE:
#   helm template myapp .
#     -f values.yaml
#     -f values-prod.yaml        ← your HELM_VALUES_FILES
#         │
#         ▼
# Output contains placeholders:
#   password: <path:secret/data/prod/keycloak#admin-password>
#         │
#         ▼
# argocd-vault-plugin generate
#   fetches real value from Vault
#         │
#         ▼
# Final output:
#   password: MyStr0ngAdminPass!   ← real secret injected ✅
#         │
#         ▼
# Applied to Kubernetes