{{- if include "database.createSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database.secretName" . }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-username: {{ .Values.auth.username | b64enc | quote }}
  postgres-password: {{ .Values.auth.password | b64enc | quote }}
  postgres-database: {{ .Values.auth.database | b64enc | quote }}
{{- end }}
