{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database.secretName" . }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-username: {{ required "database.auth.username is required" .Values.auth.username | b64enc | quote }}
  postgres-password: {{ required "database.auth.password is required" .Values.auth.password | b64enc | quote }}
  postgres-database: {{ required "database.auth.database is required" .Values.auth.database | b64enc | quote }}
{{- end }}