apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-vault-plugin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # must sync AFTER vault is running
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/seang454/jenkin-argo-gitops
    targetRevision: master
    path: argocd/avp              # AVP plugin config lives here
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
