apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  KC_DB: {{ .Values.database.vendor | quote }}
  {{- if ne .Values.database.vendor "dev-file" }}
  KC_DB_URL_HOST: {{ .Values.database.host | quote }}
  KC_DB_URL_PORT: {{ .Values.database.port | quote }}
  KC_DB_URL_DATABASE: {{ .Values.database.name | quote }}
  KC_DB_USERNAME: {{ .Values.database.username | quote }}
  KC_DB_SCHEMA: {{ .Values.database.schema | quote }}
  {{- end }}
  KC_HTTP_RELATIVE_PATH: {{ .Values.keycloak.httpRelativePath | quote }}
  KC_PROXY: {{ .Values.keycloak.proxy | quote }}
  {{- if .Values.keycloak.hostname }}
  KC_HOSTNAME: {{ .Values.keycloak.hostname | quote }}
  {{- end }}
  KC_HOSTNAME_STRICT: {{ .Values.keycloak.hostnameStrict | quote }}
  KC_HOSTNAME_STRICT_HTTPS: {{ .Values.keycloak.hostnameStrictHttps | quote }}
  KC_HEALTH_ENABLED: "true"
  KC_METRICS_ENABLED: {{ .Values.metrics.enabled | quote }}
  KC_CACHE: {{ .Values.cache.stack | quote }}
  KC_HTTP_PORT: "8080"
  KC_HTTPS_PORT: "8443"
  KC_MANAGEMENT_PORT: "9000"
