{{- if not .Values.keycloak.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.adminSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.keycloak.auth.adminPassword | b64enc | quote }}
{{- end }}
---
{{- if and (not .Values.database.existingSecret) (ne .Values.database.vendor "dev-file") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.dbSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ .Values.database.password | b64enc | quote }}
{{- end }}
